//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsa_algo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class RsaAlgoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RsaAlgoSettings defaultInstance = ((RsaAlgoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RsaAlgoSettings())));
        
        public static RsaAlgoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./")]
        public string LogPathConf {
            get {
                return ((string)(this["LogPathConf"]));
            }
            set {
                this["LogPathConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogNameConf {
            get {
                return ((string)(this["LogNameConf"]));
            }
            set {
                this["LogNameConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int KeySizeConf {
            get {
                return ((int)(this["KeySizeConf"]));
            }
            set {
                this["KeySizeConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOptimalPaddingConf {
            get {
                return ((bool)(this["UseOptimalPaddingConf"]));
            }
            set {
                this["UseOptimalPaddingConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLogsConf {
            get {
                return ((bool)(this["UseLogsConf"]));
            }
            set {
                this["UseLogsConf"] = value;
            }
        }
    }
}
